### ISSUE TITLE
Bitmap type field

### ISSUE THREAD

**Issue by Lex74** [leonhad/paradoxdriver#13]
I have an exception while loading the database. One table contains a field `Bitmap` (type 16)

**Comment by Lex74** [comment]
Oh, sorry, looks like this problem was solved in code, but not in release that I downloaded here https://github.com/leonhad/paradoxdriver/releases/tag/v1.3

**Comment by leonhad** [comment]
Hi Lex74,

You are right. I don't submit the next version because I'm in very long bug
fixes.

Thanks for the feedback anyway.

Um abraço,
Leonardo

2017-12-29 5:32 GMT-02:00 Lex74 <notifications@github.com>:
