### ISSUE TITLE
I can't get right BLOB

### ISSUE THREAD

**Issue by Lex74** [leonhad/paradoxdriver#14]
I have an image inside the database. How to get BLOB? I tried CLOB, but the result is not right.

**Comment by berry120** [comment]
Blob's don't currently seem to be supported in the library. I'm actually looking at adding support for these (need it for another project), so if you want to zip up a sample database with a BLOB and attach it here, I'll take a look at that at the same time.

**Comment by leonhad** [comment]
Fixed in 1.4.0 version.
