### ISSUE TITLE
Date fields returns 0002-12-31

### ISSUE THREAD

**Issue by JosepMariaGomez** [leonhad/paradoxdriver#18]
Date fields are returning 0002-12-31 date.
The table has "Pdox ANSI Spanish" language. 
How must I configure the driver to read rigth date info?

I've Tryed to open with charset, but doesn't works...

```
            Class.forName("com.googlecode.paradox.Driver");
//            String charset = "?charSet=cp284/1145";
//            String charset = "?charSet=cp284";
//            String charset = "?charSet=cp1145";
            String charset = "?charSet=cp1250";
            try (Connection pdxConn = DriverManager.getConnection("jdbc:paradox:" + path + charset)) {
                   // MyStuff
            }
```
```
java.sql.SQLException: Directory not found.
	at com.googlecode.paradox.ParadoxConnection.<init>(ParadoxConnection.java:107)
	at com.googlecode.paradox.Driver.connect(Driver.java:61)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
```
------
Without charset works smooth...
 ```
     try (Connection pdxConn = DriverManager.getConnection("jdbc:paradox:" + path)) {
                   // MyStuff
      }
```

TIA

**Comment by leonhad** [comment]
Hi,

This error can be a bug. Can you send it to me some example file? What
version of the driver do you use?

Regards,
Leonardo


Em sex, 18 de jan de 2019 às 13:52, JosepMariaGomez <
notifications@github.com> escreveu:

**Comment by JosepMariaGomez** [comment]
Hi Leonardo...
I'm using 1.4.0, stable.

**Comment by JosepMariaGomez** [comment]
Hi Leonardo,
I'm using 1.4.0, stable.
I've tryed to aplly the ParadoxDriver-charset.patch, but only I've received errors, in lines with '@' char...
When I apply manually (typing the code differences), I miss some lines in ParadoxConnection.java, TableData,java
Ex. missing fields in ParadoxConnection.java: 
```
 	private FileLock lock;
 	private RandomAccessFile lockFile;
        private File dir;
```
Ex. missing fields in TableData.java: 
`
isValid()

`
and so on...
It seems like there is more previuos patch files theh I've not applied.
I've loosed more patch files? where can I found they?

muito obrigado.

P.S. How can I send you a example DB file ??

**Comment by JosepMariaGomez** [comment]
SOLVED... '0002-12-31 BC' is the value for a null date

I'm sorry for inconveniences and for making waste your time...

**Comment by leonhad** [comment]
Hi,

Thanks for solving the problem and now I know how to fix it in the driver. I appreciate your help and I thank you for your effort.

In the next driver version, this problem will be fixed.

Regards,
Leonardo

De: JosepMariaGomez <notifications@github.com>
Responder para: leonhad/paradoxdriver <reply@reply.github.com>
Data: segunda-feira, 21 de janeiro de 2019 14:10
Para: leonhad/paradoxdriver <paradoxdriver@noreply.github.com>
Cc: Leonardo Alves da Costa <leonhad@gmail.com>, Comment <comment@noreply.github.com>
Assunto: Re: [leonhad/paradoxdriver] Date fields returns 0002-12-31 (#18)


SOLVED... '0002-12-31 BC' is the value for a null date

I'm sorry for inconveniences and for making waste your time...
