### ISSUE TITLE
Test for LIKE escape chars

### ISSUE THREAD

**Issue by leonhad** [leonhad/paradoxdriver#34]
The characters escapes in like expressions is wrong.

**Comment by gurshafriri** [comment]
👋 @leonhad would you say this is fixing a security issue, or just better practices? 
thanks, Gur from [Snyk](https://snyk.io).

**Comment by leonhad** [comment]
Hi, this is better practice. The driver was not accepting LIKE expressions before. Example:

SELECT * FORM TABLE WHERE A LIKE 'test%'

or 

SELECT * FORM TABLE WHERE A ILIKE 'test%'

for case insensitive.

Nothing related to security issues in this item (not in this item).
