### ISSUE TITLE
Problemas ao ler string com ascentos

### ISSUE THREAD

**Issue by GustavoAlves1993** [leonhad/paradoxdriver#36]
Boa tarde @leonhad , hoje fui utilizar a versão 1.5.0 de sua biblioteca para leitura de arquivos paradox, e me deparei com um problema, quando um campo do tipo STRING tem qualquer acentuação a mesma não é carregada corretamente, e as palavras retornam incompletas, segue alguns exemplo:

palavra TRANSMISSÃO é carregada como TRANSMISSO
palavra DIREÇÃO  é carregada como DIREO
palavra EMERGÊNCIA é carregada como EMERGNCIA

e por ai vai, se precisar que te envia a tabela que usei quando reparei esse problema, por favor me avise que te encaminho ela por e-mail ou outro canal de preferência

obrigado desde já e parabéns por esse ótima biblioteca.

**Comment by leonhad** [comment]
Olá Gustavo. Esse tipo de problema é bem comum porque as pessoas criavam as tabelas com um tipo de charset e usavam outro. Como o programa lia direto as tabelas, ele não respeitava o charset que a tabela usava.

Pergunta, esse problema acontece em uma tabela só ou em todas elas?

Se você quiser me mandar uma tabela com esse erro, posso lhe mostrar como corrigir o problema na leitura.

**Comment by leonhad** [comment]
Esqueci de avisar, nessa versão é possível setar o charset na conexão para qualquer valor suportado pelo Java. No exemplo abaixo, é um teste com um charset russo. No seu caso, acredito que seja algo como cp1252 ou ISO-8859-1, caso você queira testar diretamente.

```Java
Properties properties = new Properties();
properties.put("charset", "cp1251");

try (final Connection conn = DriverManager.getConnection(CONNECTION_STRING, properties);
    final Statement stmt = conn.createStatement();
    final ResultSet rs = stmt.executeQuery("SELECT Note FROM NOTE1251 WHERE Id=2")) {
        // Carregar os valores aqui
}
```

**Comment by GustavoAlves1993** [comment]
@leonhad isso aconteceu em um banco paradox especifico, já usei sua lib para ler alguns bancos paradox e nunca tive esse problema, hoje foi a primeira vez, até achei estranho, ai atualizei a lib e o manteve o problema, porém com sua dica consegui resolver, passei o properties com charset cp1252 antes de abrir a conexão e ele leu normalmente os acentos das palavras.

vou te enviar a tabela, se quiser dar uma olhada, vai que ajuda em algo.

muito obrigado pela ajuda

**Comment by leonhad** [comment]
Gustavo, obrigado pelo retorno.

Envia para o meu e-mail leonhad@gmail.com caso você não se importe. Isso vai ajudar na resolução de problemas futuros.
