### ISSUE TITLE
getPrecision and getScale result in same value

### ISSUE THREAD

**Issue by edwin-hendriks** [leonhad/paradoxdriver#42]
**Describe the bug**
I used `getPrecision` and `getScale` in my project. They result in the same value. The current source code in this driver also seems to suggest that `precision` is used for both.
```java
    public int getPrecision() {
        return this.precision;
    }
```
and
```java
public int getScale() {
        if (isSigned()) {
            return this.precision;
        } else {
            return 0;
        }
    }
```

**To Reproduce**
Simply use `getPrecision` and `getScale` on a numeric column that has in total 5 digits of which 2 are to the right of the decimal separator. You will see that the same value is returned.
**Expected behavior**
In this example `getPrecision` should result in 5 and `getScale` in 2

**Version tested:**
```xml
    <dependency>
      <groupId>com.googlecode.paradoxdriver</groupId>
      <artifactId>paradoxdriver</artifactId>
      <version>1.6.0</version>
    </dependency>
```
**By the way:**
Big thanks for having created this driver.

**Comment by leonhad** [comment]
Fixed in 1.6.1.

**Comment by edwin-hendriks** [comment]
Thanks Leonardo. Greatly appreciated.

**Comment by leonhad** [comment]
Thanks, the 1.6.1 version was pushed to Maven Central, please await the process to finish.
