### ISSUE TITLE
java.sql.SQLException: Invalid operator.

### ISSUE THREAD

**Issue by 824125235** [leonhad/paradoxdriver#44]
hi
I use java to connect to the *. db file shared by Windows. One can query successfully, and the other can display Invalid operator, I tried 1.6.0, which caused my jvm memory overflow

**Comment by 824125235** [comment]
Or you can give me an idea. Thank you

**Comment by leonhad** [comment]
Hi,

Can you send some stacktrace or error log, please? If you can send me any of the database files with has the problem, it can help a lot too.

**Comment by 824125235** [comment]
Hi,
The db file is sent to your email address

**Comment by 824125235** [comment]
[leonhad@gmail.com](mailto:leonhad@gmail.com)

**Comment by leonhad** [comment]
Hi,

The db file was not arrived yet.

**Comment by 824125235** [comment]
?﹏??&nbsp;_&nbsp;慢走i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leonhad/paradoxdriver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 凌晨2:04
***@***.***&gt;;
抄送:&nbsp;"✎﹏₯㎕ _ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [leonhad/paradoxdriver] java.sql.SQLException: Invalid operator. (Issue #44)





 
Hi,
 
The db file was not arrived yet.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

scjl_w.zip (10.14M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=09336633fe836cce051479021e31031e4e4700520d0806551b57020a091c550104034b510903091c540203075e0800085056030a383b314255590a6c4f1f4b5846335b&t=exs_ftn_download&code=63f38111

**Comment by 824125235** [comment]
Hi,
this db file


?﹏?? _ 慢走i
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "leonhad/paradoxdriver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 凌晨2:04
***@***.***&gt;;
抄送:&nbsp;"✎﹏₯㎕ _ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [leonhad/paradoxdriver] java.sql.SQLException: Invalid operator. (Issue #44)





 
Hi,
 
The db file was not arrived yet.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

scjl_w.zip (10.14M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=09336633fe836cce051479021e31031e4e4700520d0806551b57020a091c550104034b510903091c540203075e0800085056030a383b314255590a6c4f1f4b5846335b&t=exs_ftn_download&code=63f38111

**Comment by 824125235** [comment]
Hi,
Any special findings?

**Comment by leonhad** [comment]
Hi, I have tried your file and seems to works fine. I think the problem is in the connection string or SQL command you are using.

Can you send me the SQL you are using?

For connection string, please use something like: `jdbc:paradox:c:\directory\other`

**Comment by 824125235** [comment]
Hi,
sql:select * from scjl_w where sj > '(text)' and Note = '自动'  limit 10
"jdbc:paradox:\\SZCYTEK-483699\mixer\"

**Comment by 824125235** [comment]
Hi,
sql:select * from scjl_w where sj > '2023-02-20 00:00:00' and Note = '自动' limit 10
"jdbc:paradox:\SZCYTEK-483699\mixer"

**Comment by 824125235** [comment]
Hi,
sql:select * from scjl_w where sj > '2023-02-20 00:00:00' and Note = '自动' limit 10
"jdbc:paradox:\\SZCYTEK-483699\mixer"

**Comment by 824125235** [comment]
There was a memory overflow for a while, I don't know why it recovered on its own, now there is a new problem, I can see the date 2023-02-28 in the database, but can't query to that point in time.

**Comment by leonhad** [comment]
Hi, the problem is the field SJ that is not a date field. To convert use the DATE() function like that

select *
from scjl_w
where Note = '自动'
   and date(sj) > date('2023-02-20')

However, the memory overflows is because the file size (350MB). That is a big Paradox File. I will try optimize the memory usage based on your filesizes, but this kind of task can take a while.

**Comment by leonhad** [comment]
#45

**Comment by 824125235** [comment]
Thank you for your advice and have a nice life
