### ISSUE TITLE
Allow specify charset as url parameter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [leonhad/paradoxdriver#7]
```
Reading some old tables needs to specify charset parameter:

jdbc:paradox:/dir/to/files?charSet=cp1250

Patch is attached.

```

Original issue reported on code.google.com by `michalek...@gmail.com` on 14 Feb 2015 at 9:57

Attachments:
- [ParadoxDriver-charset.patch](https://storage.googleapis.com/google-code-attachments/paradoxdriver/issue-7/comment-0/ParadoxDriver-charset.patch)

**Comment by leonhad** [comment]
Fixed in version 1.5.0.

Use "charset" in connection properties. Example:

```Java
Properties properties = new Properties();
properties.put("charset", "cp1251");

final Connection conn = DriverManager.getConnection("jdbc:paradox:db", properties);
```
