### ISSUE TITLE
RazorSQL: Change properties is not supported yet.

### ISSUE THREAD

**Issue by TB1234** [leonhad/paradoxdriver#9]
Sorry I am no Java Developer so I don't know what happened here.

I tried to connect to a Paradox Database with RazorSQL. I selected the .jar file and use "com.googlecode.paradox.Driver" as DriverClass. I also use my directory to the Paradox Files. No user/password is used.

If i click connect, i got the error "Change properties is not supported yet.". Is this missing in the Paradox driver?

The same thing works with the hxtt demo driver.

Thanks and merry christmas

**Comment by leonhad** [comment]
Hi Tobias,

I will test the driver with RazorSQL as soon as possible.

**Comment by leonhad** [comment]
Fixed in 1.3 version.

**Comment by leonhad** [comment]
Hi Tobias,

I try to fix some code in hope to fix this issue.

You can get the new version in https://github.com/leonhad/paradoxdriver/releases/latest or wait the Maven Central to publish the new 1.3 version.

Regards,
Leonardo Costa

**Comment by TB1234** [comment]
Hello Leonardo,

thank you! :-) The driver works with RazorSQL 7.1.4 in the most cases. Newer versions not. But I think the problems are not ones of the driver because I can reproduce it with the HXTT driver as well.

I informed RazorSQL about the problem.

Regards,
Tobias
